### ISSUE TITLE
After installing on Debian 8 sample gw/cube makes PSP freeze

### ISSUE THREAD

**Issue by nikmes** [pspdev/psptoolchain#65] opened 2016-02-28 15:40 UTC
I can confirm that with older version of the SDK the samples work fine. Specificaly the gu/cube sample. Is there any update that i should do in Makefiles or somewhere. I notice that samples that are not using images and textures work fine.

**Comment by DaveeFTW** [comment] 2016-05-20 20:32
This is an issue I came across too. libgcc for 4.9 does not generate proper software routines for handling double->float conversions. The lazy fix I did was copying over libgcc from an older installation.

**Comment by carstene1ns** [comment] 2016-06-16 21:29
I also had this problem. I am currently using GCC 4.8.5 rebased from #61, which works fine.

**Comment by nikmes** [comment] 2016-08-10 13:11
Thyanks. I will also try that.

**Comment by wickles** [comment] 2016-09-20 18:48
@carstene1ns worked for me, thanks!

**Comment by dbeef** [comment] 2020-04-17 22:58
As linked PR's are merged, I suspect that the problem is fixed;
however, as we have just updated toolchain to use GCC 9.3.0, please report any persisting problems under:

https://github.com/pspdev/pspsdk/issues/26

**Closed by dbeef** 2020-04-17 22:58 UTC
