### ISSUE TITLE
psp-gcc: error: unrecognized command line option '-mno-crt0'

### ISSUE THREAD

**Issue by belldandu** [pspdev/psptoolchain#78] opened 2017-04-08 19:29 UTC
I'm not sure if the sdk is broken because opentri #72 fails to install or not but i've tried ubuntu 12.04 and ubuntu 14.04

This is within a docker image https://github.com/Belldandu/Docker-PSP/

**Comment by belldandu** [comment] 2017-04-08 19:40
Also a couple of ls commands say no such file or directoy for some files.

**Comment by belldandu** [comment] 2017-04-08 20:26
And debian 7.11 also gives the same problems.
debian 8.7 doesn't have automake1.9 so not bothering.

**Comment by belldandu** [comment] 2017-04-08 22:33
Compile log (10MB of text) https://ilp.moe/compile.log

**Comment by belldandu** [comment] 2017-04-09 00:16
Line 56982 is the start of the error

**Comment by belldandu** [comment] 2017-04-09 01:24
tail -n 4260 compile.log | head -n 100

**Comment by belldandu** [comment] 2017-04-09 01:25
```
belldandu@Cake:~/Docker-PSP$ tail -n 4260 compile.log | head -n 100                                                                                      In file included from /home/container/pspdev/psp/include/libpng15/png.h:449:0,                                                                                            from triImage.c:37:                                                                                                                     /home/container/pspdev/psp/include/libpng15/png.h:2200:1: note: expected 'int *' but argument is of type 'triS32 *'                                       PNG_EXPORT(151, png_uint_32, png_get_PLTE,                                                                                                               ^                                                                                                                                                       triImage.c:603:44: warning: passing argument 4 of 'png_get_tRNS' from incompatible pointer type                                                              png_get_tRNS(png_ptr, info_ptr, &trans, &num_trans, &trans_values);                                                                                                                              ^                                                                                                            In file included from /home/container/pspdev/psp/include/libpng15/png.h:449:0,                                                                                            from triImage.c:37:                                                                                                                     /home/container/pspdev/psp/include/libpng15/png.h:2288:1: note: expected 'int *' but argument is of type 'triS32 *'                                       PNG_EXPORT(166, png_uint_32, png_get_tRNS,                                                                                                               ^                                                                                                                                                       triTexman.c: In function 'triNearestColorIndex':                                                                                                         triTexman.c:820:1: error: unrecognizable insn:                                                                                                            }                                                                                                                                                        ^                                                                                                                                                       (insn 237 236 238 37 (set (reg:SI 477)                                                                                                                           (if_then_else:SI (ne:CC (reg:CC 67 $fcc0)                                                                                                                        (const_int 0 [0]))                                                                                                                                   (reg/v:SI 281 [ minIndex ])                                                                                                                              (reg/v:SI 265 [ minIndex ]))) -1                                                                                                                  (nil))                                                                                                                                              triTexman.c:820:1: internal compiler error: in extract_insn, at recog.c:2202                                                                             triImage.c: In function 'triImageAnimationSaveTri':                                                                                                      triImage.c:2546:12: warning: unused variable 'nframe' [-Wunused-variable]                                                                                     triS32 nframe = 0;                                                                                                                                              ^                                                                                                                                            triGraphics.c: At top level:                                                                                                                             triGraphics.c:94:15: warning: 'triColorKey' defined but not used [-Wunused-variable]                                                                      static triS32 triColorKey = 0;                                                                                                                                         ^                                                                                                                                         triGraphics.c:95:15: warning: 'triBlend' defined but not used [-Wunused-variable]                                                                         static triS32 triBlend = 0;                                                                                                                                            ^                                                                                                                                         triImage.c: At top level:                                                                                                                                triImage.c:438:15: warning: 'next_mul' defined but not used [-Wunused-function]                                                                           static triS32 next_mul(triU32 w, triU32 n)                                                                                                                             ^                                                                                                                                         psp-gcc -I. -I/home/container/pspdev/psp/sdk/include -O3 -G0 -Wall -D__PSP__ -DTRI_SUPPORT_PNG -DTRI_SUPPORT_FT -I/home/container/pspdev/psp/include/freetype2 -I/home/container/pspdev/psp/include -D_PSP_FW_VERSION=150   -c -o triModel.o triModel.c                                                           psp-gcc -I. -I/home/container/pspdev/psp/sdk/include -O3 -G0 -Wall -D__PSP__ -DTRI_SUPPORT_PNG -DTRI_SUPPORT_FT -I/home/container/pspdev/psp/include/freetype2 -I/home/container/pspdev/psp/include -D_PSP_FW_VERSION=150   -c -o triInput.o triInput.c                                                           triModel.c: In function 'triModelsLoadTrim':                                                                                                             triModel.c:355:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]                                           switch (*(triU32*)tch.magic)                                                                                                                             ^                                                                                                                                                     triModel.c: In function 'triMeshOptimize':                                                                                                               triModel.c:1005:2: warning: implicit declaration of function 'sceKernelDcacheWritebackAll' [-Wimplicit-function-declaration]                               sceKernelDcacheWritebackAll();                                                                                                                           ^                                                                                                                                                      triModel.c:864:9: warning: unused variable 'i' [-Wunused-variable]                                                                                         triS32 i, j;                                                                                                                                                    ^                                                                                                                                               triModel.c:809:33: warning: variable 'verPad' set but not used [-Wunused-but-set-variable]                                                                 triS32 texPad, colPad, norPad, verPad;                                                                                                                                                  ^                                                                                                                       triModel.c:809:25: warning: variable 'norPad' set but not used [-Wunused-but-set-variable]                                                                 triS32 texPad, colPad, norPad, verPad;                                                                                                                                          ^                                                                                                                               triModel.c:809:17: warning: variable 'colPad' set but not used [-Wunused-but-set-variable]                                                                 triS32 texPad, colPad, norPad, verPad;                                                                                                                                  ^                                                                                                                                       triModel.c:809:9: warning: variable 'texPad' set but not used [-Wunused-but-set-variable]                                                                  triS32 texPad, colPad, norPad, verPad;                                                                                                                          ^                                                                                                                                               triModel.c:807:9: warning: unused variable 'verSize' [-Wunused-variable]                                                                                   triS32 verSize = (format&GU_VERTEX_BITS)?((format&GU_VERTEX_32BITF)==GU_VERTEX_32BITF?4:((format&GU_VERTEX_BITS)>>7)):0;                                        ^                                                                                                                                               triModel.c:806:9: warning: unused variable 'norSize' [-Wunused-variable]                                                                                   triS32 norSize = (format&GU_NORMAL_BITS)?((format&GU_NORMAL_32BITF)==GU_NORMAL_32BITF?4:((format&GU_NORMAL_BITS)>>5)):0;                                        ^                                                                                                                                               triModel.c:805:9: warning: unused variable 'colSize' [-Wunused-variable]                                                                                   triS32 colSize = (format&GU_COLOR_BITS)?((format&GU_COLOR_8888)==GU_COLOR_8888?4:2):0;                                                                          ^                                                                                                                                               triModel.c:804:9: warning: unused variable 'texSize' [-Wunused-variable]                                                                                   triS32 texSize = (format&GU_TEXTURE_BITS)!=0?((format&GU_TEXTURE_32BITF)==GU_TEXTURE_32BITF?4:((format&GU_TEXTURE_BITS))):0;                                    ^                                                                                                                                               0x7f2eea _fatal_insn(char const*, rtx_def const*, char const*, int, char const*)                                                                                 ../../gcc/rtl-error.c:109                                                                                                                        0x7f2f19 _fatal_insn_not_found(rtx_def const*, char const*, int, char const*)                                                                                    ../../gcc/rtl-error.c:117                                                                                                                        0x7c1f70 extract_insn(rtx_def*)                                                                                                                                  ../../gcc/recog.c:2202                                                                                                                           0x696b03 instantiate_virtual_regs_in_insn                                                                                                                        ../../gcc/function.c:1559                                                                                                                        0x696b03 instantiate_virtual_regs                                                                                                                                ../../gcc/function.c:1925                                                                                                                        0x696b03 execute                                                                                                                                                 ../../gcc/function.c:1975                                                                                                                        Please submit a full bug report,                                                                                                                         with preprocessed source if appropriate.                                                                                                                 Please include the complete backtrace with any bug report.                                                                                               See <http://gcc.gnu.org/bugs.html> for instructions.                                                                                                     make: *** [triTexman.o] Error 1                                                                                                                          make: *** Waiting for unfinished jobs....                                                                                                                In file included from streams/streams.c:17:0:                                                                                                            streams/bstream.inc: In function 'bstream_write':                                                                                                        streams/bstream.inc:254:19: warning: 'bits' may be used uninitialized in this function [-Wmaybe-uninitialized]                                               m->buf1 = bits >> (8 - m->bpos) | (m->buf2 & ~((1 << m->bpos)-1));                                                                                                      ^                                                                                                                                     Failed installing opentri!                                                                                                                               belldandu@Cake:~/Docker-PSP$```

**Comment by belldandu** [comment] 2017-04-09 18:53
After looking into this it is exactly the same problem as #72 so closing.

**Comment by belldandu** [comment] 2017-04-09 21:16
Just tested #72 's fix and although opentri installs now i still get this error when compiling https://github.com/MrColdbird/aemu
 psp-gcc: error: unrecognized command line option '-mno-crt0'

So reopening

**Comment by SamRH** [comment] 2017-08-15 11:32
I think -nostartfiles (see https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html for details) might be an equivalent flag. Otherwise looking at how other platforms have implemented this flag (https://gcc.gnu.org/ml/gcc-patches/2012-09/msg01572.html) it seems like quite a minor addition. I might have a play around this weekend.

**Comment by ticky** [comment] 2018-08-18 04:38
Is there any likelihood that this issue is going to be addressed? It appears to me like a major issue blocking use of the toolchain to build plugins.

**Comment by fjtrujy** [comment] 2018-09-22 10:32
I'm still suffering the same issue even after merge this PR https://github.com/pspdev/pspsdk/issues/24

Must be something else...

**Comment by ticky** [comment] 2018-09-22 17:46
@fjtrujy I’ve just tested with my docker-pspdev image, and my prx builds are working again. You may need to double check that reinstalling is not leaving behind the old `build_prx.mak` file (check in `$PSPSDK/lib/build_prx.mak`), and that what you’re building doesn’t otherwise add `-mno-crt0` itself!

**Comment by fjtrujy** [comment] 2018-09-23 13:30
Hello,
I didn't tested yet in the docker, but in this case I'm trying to use on OSX 10.13 and compiling the RetroArch project, and I'm still suffering this.

@ticky can you give a try and compile the RetroArch for the PSP? just to see if it is really fixed?

Thanks

**Comment by ticky** [comment] 2018-09-23 22:11
@fjtrujy could you please confirm whether the mno-crt0 is still present at the path I specified before? Also check whether that flag is specified in the Makefiles of the project you’re building. I don’t have my computer on hand, or time to build random things right now!

**Comment by fjtrujy** [comment] 2018-09-24 14:40
Hello,
So if you are asking if the `build_prx.mak` contains the `-mno-crt0`, you are right, is not there. 
About the project that I'm trying to compile is suffering exactly the same error that we were discussing over here, the thing is, the project doesn't contains the `-mno-crt0` option however contains the `-nostartfiles` flag.

By the way I have been trying to compile also using Ubuntu 18.04 and I have also suffering exactly the same issue.

Thanks

**Comment by carstene1ns** [comment] 2018-09-24 15:51
Clean up your build environment and do a clean checkout of the SDK and your project. The flag needs to be included somewhere, it does not magically insert itself.

**Comment by fjtrujy** [comment] 2018-09-24 16:14
Hello,
I never said that the flags was over there, actually I'm pretty sure that the flag is not there.
Also yesterday I did a clean full linux installation in a different computer and I have experimented the same issue.

So maybe it is some thing else.

```
In file included from griffin/griffin.c:842:0:
griffin/../gfx/video_filters/phosphor2x.c: In function ‘phosphor2x_work_cb_xrgb8888’:
griffin/../gfx/video_filters/phosphor2x.c:420:1: error: unrecognizable insn:
 }
 ^
(insn 154 153 155 22 (set (reg:SI 386 [ D.209986 ])
        (if_then_else:SI (ne:CC (reg:CC 67 $fcc0)
                (const_int 0 [0]))
            (reg:SI 386 [ D.209986 ])
            (reg:SI 396))) -1
     (nil))
griffin/../gfx/video_filters/phosphor2x.c:420:1: internal compiler error: in extract_insn, at recog.c:2202

griffin/../gfx/video_filters/phosphor2x.c:420:1: internal compiler error: Abort trap: 6
psp-gcc: internal compiler error: Abort trap: 6 (program cc1)
make: *** [griffin/griffin.o] Abort trap: 6
```

This is the error that I have in the `RetroArch` project.

**Comment by ticky** [comment] 2018-09-24 16:19
That is a *completely different* error. There’s no reference to `-mno-crt0` in it at all.

**Comment by artart78** [comment] 2018-09-24 16:27
@fjtrujy what's around line 420 in gfx/video_filters/phosphor2x.c? Please open another issue here if you have good reasons thinking it's a bug of the toolchain and not RetroArch (if you can compile the same version of RetroArch with an older toolchain, the best being if you can tell which commit of the toolchain made stuff break), anyway I'm closing this one

**Closed by artart78** 2018-09-24 16:27 UTC

**Comment by ticky** [comment] 2018-09-24 16:29
@fjtrujy I suspect the error you’re encountering is *actually* that described by #72 (linked earlier in the thread regarding the error you’re seeing)

**Comment by fjtrujy** [comment] 2018-09-24 16:54
Hello @ticky ,
Probably you are right, I was seeing how people were linking #72 and #77 and #78, so actually not sure  where the solution and issue were...

I just can say if it useful, that the issue dissapear when I change the compilation flags from `-O3` to `-O2`

Hello @artart78, I don't know the commit that may break the compilation, anyway I'm starting to think that maybe the issue is in the `RetroArch` project and not here.

Thanks you very much for all the caos that I have created.
