### ISSUE TITLE
Fail installing openal

### ISSUE THREAD

**Issue by latot** [pspdev/psptoolchain#64] opened 2016-02-14 14:33 UTC
Hi all, well i try installing but i get that error, all info is in the gist, the path, vars exported, builds etc:

https://gist.github.com/latot/ac3377e6e9ea2eb2779f

i use Gentoo 64

**Comment by Fordi** [comment] 2016-06-03 03:36
Looks like the problem is that one of the examples is leveraging local system libs.

After psplibraries is cloned, you'll need to edit psplibraries/scripts/openal.sh to add "-D EXAMPLES=OFF"

**Comment by latot** [comment] 2016-12-06 18:01
Hi, thx the answer, testing sadly didn't works disable the examples..., the conflict is here:

```
[  3%] Building C object CMakeFiles/openal.dir/OpenAL32/alAuxEffectSlot.obj
In file included from /home/pipe/Documentos/git/psptoolchain/build/psplibraries/build/openal-soft-1.14/OpenAL32/alAuxEffectSlot.c:28:0:
/home/pipe/Documentos/git/psptoolchain/build/psplibraries/build/openal-soft-1.14/OpenAL32/Include/alMain.h:114:9: error: unknown type name ‘pthread_mutex_t’
 typedef pthread_mutex_t CRITICAL_SECTION;
```

**Comment by khuenqdev** [comment] 2019-09-16 04:37
Hey there, is there any update to this issue? I couldn't compile openal because of pthread_mutex_t error :(

**Comment by Sanaki** [comment] 2019-11-19 05:18
Having the same issue. Don't suppose there's much hope at this point, but any hint would be nice. I'm assuming it's related to compiling on a 64-bit system.

[Log of openal compilation failure](https://github.com/pspdev/psptoolchain/files/3862010/openal_log.txt)

**Comment by mirh** [comment] 2019-11-22 22:42
Guys on stack suggest to try also including sys/types.h 
Besides, you could try the [newer toolchain](https://github.com/mrneo240/psptoolchain) I guess?

And last but not least, I [see](https://aur.archlinux.org/cgit/aur.git/commit/?h=psp-newlib&id=180c2012820be7a1123846fcb90c984e4451e402) not all [pthreads](https://github.com/jschmidlapp/pthreads-emb) are made the same.

**Comment by Sanaki** [comment] 2019-11-23 08:40
Sadly, the newer toolchain didn't do the trick. Though it is nicer in general, openal still fails, first because cmake-toolchain-script supposedly failed (when built alone it supposedly succeeds), and if that line is removed from the dependency check it once again fails on the pthread mutex.

**Comment by mirh** [comment] 2019-11-23 13:23
Ok, then as I said try to either include types.h (even though it's odd.. pthread should [already](https://sourceware.org/git/gitweb.cgi?p=newlib-cygwin.git;a=blob;f=newlib/libc/include/pthread.h;hb=refs/tags/newlib-1_20_0) think to it)
Or try [pthreads-emb](https://github.com/jschmidlapp/pthreads-emb/blob/master/pthread.h)

**Comment by mirh** [comment] 2020-05-01 20:53
Likely fixed by https://github.com/pspdev/psplibraries/pull/34

**Comment by latot** [comment] 2020-05-02 20:54
Hi, i don't know if is really solved, because now, the examples are broken D;

But at least, is a way to can compile this :)

**Comment by carstene1ns** [comment] 2020-05-03 08:25
@latot You can likely compile the examples, if you add psp specific buildflags and edit the source slightly.
But there really is no point in doing that here, since these are not needed for the toolchain.

I am closing this here, since it should be fixed for everything not Debian 10, where we have a dedicated issue:
https://github.com/pspdev/psplibraries/issues/53

**Closed by carstene1ns** 2020-05-03 08:25 UTC
